### ISSUE TITLE
could not run frisby test sequentially using Jasmine

### ISSUE THREAD

**Issue by styrus** [vlucas/frisby#562] opened 2020-05-25 13:11 UTC
Hi I am using Frisby v2 with jasmine.
I am facing problem in running tests which are like

```
var frisby = require('frisby');
let token;

it ('VALUE generation with setup method',  function () {
    return frisby
    .setup({
      })
    .get("url/token")
    .expect('status', 200)
});

frisby.globalSetup({
    request: {
        headers: {
            'Authorization': 'Bearer ' +token,
            'header':'value'
        }
    }
});

it('make call USING GLOBAL SETUP' , function() {
    console.log('########### In IT  call ###########')
   return frisby
        .post('url/call', 
        {
			json body
		})
        .expect('status', 200);
    });

```
so first _it block_ testcase with **Setup()** gets **Passed** and second _it block_. after **globalSetup** is getting failed.
and this is because it runs my second test first and then it goes for first test.

how can I handle this so that it runs sequentially.
**error is for token is undefined.** as it does not find token first.

**Comment by vlucas** [comment] 2020-05-26 15:45
Frisby tests cannot be run sequentially, and your test suite should never depend on the order of tests that are run.

If there is setup you need to do for each successive test in your suite, you have a few options. You can use `frisby.use(withTokenAuth).get(...).expect(...)` in each test you need it in. Your `withTokenAuth` function might look like this:

```javascript
function withTokenAuth(spec) {
  const token = '123abc';

  return spec.setup({
    request: {
      headers: {
        'Authorization': 'Bearer ' +token,
        'header':'value'
      }
    }
  });
}
```

You can also just use the `setup` method directly in each test as well.

**Comment by styrus** [comment] 2020-05-27 11:39
Thanks @vlucas .
cant I run my tests sequentially using JEST aslo using -i option with it.

**Comment by H1Gdev** [comment] 2020-05-30 01:09
- It looks like you haven't set `token` in first `it` block.
- `-i` option is enabled in case of multiple test files in `jest`.

**Comment by styrus** [comment] 2020-06-18 12:53
@vlucas Thanks for your response.
with your solution I am trying some modification like.

const token = '123abc'; // **ie I need to take token from one of my method which returns me a token.**
so code is something like 
```
function withTokenAuth(spec) {
  const token = getToken(); //my method from which I ma getting token value.
console.log(token);  // this lines prints token value

  return spec.setup({
    request: {
      headers: {
        'Authorization': 'Bearer ' +token,
        'header':'value'
      }
    }
  });
}
```
-------------------------
now I have written a method which uses withTokenAuth() call for operation...

```
postCall(url,body){

return frisby
    .use(withTokenAuth) // USE the `withTokenAuth` function here in your test (and in every test you need it in)
    .post('url/call', 
    {
      // json body
    })
    .expect('status', 200);
)

```

**Now when I call postCall(url,body) passing all required parameters in my spec file I am getting** 
```

Response: FrisbyResponse {
  _response: Response {
    size: 0,
    timeout: 15000,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'URL',
      status: 415,
      statusText: 'Unsupported Media Type',
      headers: [Headers],
      counter: 0
    }
  },
  _body: ''
}

FAILURE Status: 415
Body:

Message:
    AssertionError: HTTP status 200 !== 415
  Stack:
    AssertionError [ERR_ASSERTION]: HTTP status 200 !== 415
        at FrisbySpec.status (\frisby\src\frisby\expects.js:25:12)
        at \node_modules\frisby\src\frisby\spec.js:418:23
        at \node_modules\frisby\src\frisby\spec.js:247:34
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

can you please let me know why I am getting this. Though all header getting set.

**Comment by styrus** [comment] 2020-06-22 13:36
@vlucas can you please provide your input on this.
thanks in advance

**Comment by H1Gdev** [comment] 2020-06-22 21:36
HTTP status `415` has wrong `Content-Type`.
What is `Content-Type` of request set to ?
Have you changed `Content-Type` in `globalSetup` ?

**Comment by styrus** [comment] 2020-06-23 06:43
@vlucas when I am passing token as the hard coded value and calling postCall (url,body) it works.

But it gives **415 response** when I am passing my token from method call.
 **Note** : this method for token generation is in another file and this method also uses .setup() for passing headers. 
Here only one header is different which required a **admin header** than withTokenAuth1().

I am not using global setup in this case. using only setup in both token method and in withTokenAuth1().

Is it like setup headers from token method are passed to withTokenAuth1() also ??
As in withTokenAuth1() I donot require **admin header**

**Comment by H1Gdev** [comment] 2020-06-23 07:04
Is there issues with `getToken()` ?

**Comment by styrus** [comment] 2020-06-30 13:57
@vlucas can you please provide you thought on this.
thanks in advance

**Comment by styrus** [comment] 2020-06-30 13:58
@H1Gdev if you check my comment above getToken() works fine and returns me token.

**Comment by vlucas** [comment] 2020-06-30 20:08
Can you dump the request headers so we can see what is actually being sent? 415 is a response from your server, and we cannot debug that or provide support for it.

Also:
```
return spec.setup({
    request: {
      headers: {
        'Authorization': 'Bearer ' +token,
        'header':'value' // Did you remember to delete this line? This was just an example...
      }
    }
  });
``

**Comment by styrus** [comment] 2020-07-02 08:56
@vlucas thanks for response
For token creation function I am using these set of headers
```
 'Authorization': 'Basic ' + Buffer.from("sysadmin:sysadmin").toString('base64'),
 'ouc_header':'admin',
'Content-Type': 'application/scim+json'
```
token from above I use in below 
and for method withTokenAuth() these are header that are required
```
'Authorization': Bearer  TOKEN,
 'ouc_header':'non_admin',
 'Content-Type': 'application/scim+json'
```
NOTE: 
When I call these mthod independently it works fine.

**Comment by H1Gdev** [comment] 2020-07-02 11:40
> When I call these method independently it works fine.

Please paste each code.

**Comment by styrus** [comment] 2020-07-02 14:25
@H1Gdev @vlucas Please find code snippet I am using.
```

function getToken(url){
 
 return frisby
       .setup({
           request:{
               headers: 
               {
                'Authorization': 'Basic ' + Buffer.from("username:password").toString('base64'),
				'ouc_header':'admin',
				'Content-Type': 'application/scim+json'
            },
              
           }
         })
		 
       //body : this method works fine
    });   
	});

```	
	**============= new file where I am calling getToken() to get my token.**	
	
```
function withTokenAuth1(spec) {    
    
`const instance_token= getToken(url);

    return spec.setup({
      request: {
        headers: 
                {
                  'Authorization': 'Bearer '+instance_token,
                  'ouc_header':'non_admin',
				  'Content-Type': 'application/scim+json'
                }
                
      }
    });
  }




   function  postCalltest()(){
     
    return frisby
        .use(withTokenAuth1)
		//body
             })
}
```

//

**now I am calling this postCalltest()() in my spec ...and then getToken() returns me token as console show it.**

**After that I am getting this.**

```
Request Headers:
        Content-Type: application/scim+json
        User-Agent: frisby/2.1.2 (+https://github.com/vlucas/frisby)
        Authorization: Basic jhkjhkhkhkk=
        ouc_header: admin

//header from getToken method


FAILURE Status: 401
JSON: {
    "response": [          //this is from withTokenAuth1() as i am calling it in postCalltest()()
        "value:Error"
    ],
    "status": 401,
    "scimType": "invalidValue",
    "detail": "Attribute \"ouc_header\" is required."   //not sure why it is not able to set header here for token and ouc_header
}
F*

```
```
Failures:
1) Token Suite Add operation
  Message:
    AssertionError: HTTP status 200 !== 415
```

I am not sure why it is not able to set header in withTokenAuth1() for **ouc_header** or **token**

**Comment by vlucas** [comment] 2020-07-03 16:12
We cannot debug your server response for you. This is not a free support forum.

I am closing this issue for now.

You can re-open it If you can give us code for both server and client in an isolated and reproducible way that proves the issue with the Frisby library itself, then we can help with a fix. Otherwise, we cannot spend any more time on this issue.

**Closed by vlucas** 2020-07-03 16:12 UTC

**Comment by H1Gdev** [comment] 2020-07-04 04:38
I can't understand this code:confused:
At the very least, make code that completes `frisby`.
(For example, list tests that pass and fail.)

**Comment by styrus** [comment] 2020-07-06 05:50
@H1Gdev @vlucas 
you can close this this ticket if you want...but could not understand what you can not get of code snippet.

It clearly shows like headers handling is an issue when it getting passed from **getToken(url)** [this method returns token from body reponse.] to **withTokenAuth1().**

Now withTokenAuth1() method setups the header to be used for different rest method ie.  postCalltest().

Well if you dont want to debug thats okay.
thanks for your time.

**Comment by H1Gdev** [comment] 2020-07-06 11:46
@styrus 

> getToken(url) [this method returns token from body reponse.]

https://github.com/vlucas/frisby/issues/562#issuecomment-653037794

`getToken(url)` returns `frisby` (that is, Promise).

I don't know how to give advice because the code is incomplete like this...

**Comment by styrus** [comment] 2020-07-06 11:52
@H1Gdev check this code sinppet for getToken(url)

```
getToken(URL){
   return frisby
    .setup
        ({
            request:
                {
                    headers: 
                        {
                            'Authorization': 'Basic ' + Buffer.from("usrname:pwd").toString('base64'),
                            'ouc_header':'admin',
                            'Content-Type': 'application/scim+json'
                        }
                }
    })
    .get(apiURL)
    .inspectResponse()
    .inspectRequestHeaders()
    .expect('status', 200)
    .then(res => {
        var token=res._token;
        console.log(token);
    });    
} 
```

is it now clear ???

**Comment by vlucas** [comment] 2020-07-06 19:40
We need both the client and server code to help you. We need an independent code repository that we can clone and run that has both the server and frisby tests for it.

One test that shows where it is working.
One test that shows where it is not.

You can all the code and the full context so it might be clear to you, but it is not clear at all to us.

**Comment by H1Gdev** [comment] 2020-07-23 23:38
It's no good returning `Promise`.
If you use `async` and `await` like below, you will get the expected behavior.

```js
async function getToken(URL) {
   return frisby
    .setup
        ({
            request:
                {
                    headers: 
                        {
                            'Authorization': 'Basic ' + Buffer.from("usrname:pwd").toString('base64'),
                            'ouc_header':'admin',
                            'Content-Type': 'application/scim+json'
                        }
                }
    })
    .get(apiURL)
    .inspectResponse()
    .inspectRequestHeaders()
    .expect('status', 200)
    .then(res => {
        var token=res._token;
        console.log(token);
        return token;
    });
}
```

```js
const instance_token= await getToken(url);
```

But first, it's better to understand [Promise of JavaScript](https://developer.mozilla.org/docs/Web/JavaScript/Guide/Using_promises).
