### ISSUE TITLE
npm package is outdated

### ISSUE THREAD

**Issue by nederdirk** [vlucas/frisby#230] opened 2015-05-15 08:51 UTC
The latest version in NPM is 0.8.5, dating back 4 months. Is it possible to get a point-release with at least the bugfixes since that time?
Changes can be found at https://github.com/vlucas/frisby/compare/v0.8.5...master

(full disclosure: I just stumbled upon a bug that I already patched (PR #193) and noticed the patch was not yet in the NPM version)

**Comment by RBLU** [comment] 2015-06-04 09:35
+1, need to reference github#master directly currenty in package.json

**Comment by vlucas** [comment] 2015-06-05 23:20
The problem is the `master` branch right now has been updated for Jasmine 2.0, and the current 0.8.5 release is Jasmine 1.0, so I can't just tag a new release and publish it without breaking the way everyone runs tests. I have to manually cherry-pick updates on the Jasmine 1.0 code, and then publish to NPM, so that's why it has not been updated in a while. I plan to publish a new 0.9.x branch soon with all the new stuff + Jasmine 2.0 support soon.

**Comment by devourment77** [comment] 2015-10-13 21:08
I would really like this too.  For now I'll use npm install git+https://github.com/vlucas/frisby.git --save-dev

**Comment by kenmazhao** [comment] 2016-01-04 10:32
@devourment77 
Great preview guide
Look forwards to 0.9.x to support Jasmine 2.0, it helps a lot.

**Comment by vlucas** [comment] 2017-07-26 16:30
Frisby v2 is currently in alpha, installable with `npm install frisby@next --save-dev`. It will be released as a proper v2.0 very soon.

**Closed by vlucas** 2017-07-26 16:30 UTC
